version: '2'
services:
    radar-auth-backend:
        image: auth-test:latest
        depends_on:
          - auth-postgresql
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgresql:5432/deviceauthorizer
            - SPRING_DATASOURCE_USERNAME=radarcns
            - SPRING_DATASOURCE_PASSWORD=radarcns
            - DEVICE_AUTHORIZER_DEVICE_CLIENTS_FILE_PATH=app-includes/device_clients_configs.yml
            - APP_SLEEP=10 # gives time for the database to boot before the application
#        ports:
#            - 8080:8080
        volumes:
            - ./etc:/app-includes
    auth-postgresql:
        image: postgres:9.6.2
#        ports:
#          - "5432:5432"
        environment:
          - POSTGRES_USER=radarcns
          - POSTGRES_PASSWORD=radarcns
          - POSTGRES_DB=deviceauthorizer

    radar-auth-frontend:
        image: auth-front:latest
        depends_on:
          - radar-auth-backend
          - auth-postgresql
        ports:
          - "3000:80"
