version: '2'
services:
    postgresql:
        image: postgres:10.4-alpine
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=radarcns
          - POSTGRES_PASSWORD=radarcns
          - POSTGRES_DB=deviceauthorizer
